# Generated by Django 4.1.1 on 2023-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=130)),
                ('Time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
