# Generated by Django 4.1.1 on 2023-04-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='SNo',
            new_name='sno',
        ),
    ]
